{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dev-apm.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-apm.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.auth.jwtSecret | default (randAlphaNum 64) | quote }}
  admin-password: {{ .Values.auth.adminUser.password | quote }}
{{- end }}
