{{- if .Values.global.registry.username }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-pull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dev-apm.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}"
    .Values.global.registry.server
    .Values.global.registry.username
    .Values.global.registry.password
    (printf "%s:%s" .Values.global.registry.username .Values.global.registry.password | b64enc)
    | b64enc }}
{{- end }}
